<?php
// $Id: content_permissions.install,v 1.1 2010/06/29 07:05:25 sajal Exp $

/**
 * @file
 * Implementation of hook_install().
 */
function content_permissions_install() {
  drupal_set_message(t('Please <a href="!url">configure your field permissions</a> immediately. All fields are inaccessible by default.', array('!url' => url('admin/user/permissions', array('fragment' => 'content_permissions')))));
}